# Generated by Django 6.0.6 on 2026-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auditlog_reporttemplate_shipment_tapeinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volser', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('rfid_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tape_type', models.CharField(choices=[('LTO-6', 'LTO-6'), ('LTO-7', 'LTO-7'), ('LTO-8', 'LTO-8'), ('LTO-9', 'LTO-9')], max_length=10)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Retained', 'Retained'), ('Off-Site', 'Off-Site'), ('In Transit', 'In Transit'), ('Scratch Eligible', 'Scratch Eligible'), ('Damaged', 'Damaged'), ('Missing', 'Missing')], default='Active', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('retention_end_date', models.DateField()),
                ('legal_hold', models.BooleanField(default=False)),
                ('audit_hold', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
    ]
