# Generated by Django 6.0.6 on 2026-06-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0003_tape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('auditor', 'Auditor'), ('backup_administrator', 'Backup Administrator'), ('operations_manager', 'Operations Manager'), ('security_officer', 'Security Officer'), ('system_administrator', 'System Administrator')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Role Template',
                'verbose_name_plural': 'Role Templates',
            },
        ),
    ]
