# Generated by Django 6.0.6 on 2026-06-19 13:49

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_customuser_verified_customuser_verified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-shipment_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='eta',
        ),
        migrations.AddField(
            model_name='shipment',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], max_length=30),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='number_of_tapes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='priority_level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiving_custodian',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiving_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='release_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='releasing_custodian',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('Off-Site Transfer', 'Off-Site Transfer'), ('Return', 'Return'), ('Retrieval', 'Retrieval'), ('Destruction', 'Destruction')], default='Off-Site Transfer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='source_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tapes',
            field=models.ManyToManyField(blank=True, related_name='shipments', to='inventory.tape'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.CharField(default=inventory.models.generate_shipment_id, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
