# Generated by Django 6.0.6 on 2026-06-19 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_shipment_options_remove_shipment_eta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_retention_days', models.PositiveIntegerField(default=90)),
                ('shipment_notification_enabled', models.BooleanField(default=True)),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('allow_offsite_transfers', models.BooleanField(default=True)),
                ('max_tapes_per_shipment', models.PositiveIntegerField(default=50)),
                ('audit_logging_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('audit_retention_years', models.PositiveIntegerField(default=7)),
                ('default_dashboard_section', models.CharField(choices=[('inventory', 'Inventory'), ('shipments', 'Shipments'), ('reports', 'Reports'), ('audit', 'Audit Logs')], default='inventory', max_length=50)),
                ('maintenance_window_start', models.TimeField(default=datetime.time(2, 0))),
                ('maintenance_window_end', models.TimeField(default=datetime.time(4, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Setting',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
