# Generated by Django 6.0.6 on 2026-06-22 06:28

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_applicationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_id', models.CharField(default=inventory.models.generate_reconciliation_id, editable=False, max_length=20, unique=True)),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation',
                'verbose_name_plural': 'Reconciliations',
                'ordering': ['-reconciliation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('Missing', 'Missing'), ('Misplaced', 'Misplaced'), ('Unexpected', 'Unexpected'), ('Duplicate', 'Duplicate'), ('Damaged', 'Damaged'), ('None', 'None')], default='None', max_length=20)),
                ('expected_location', models.CharField(blank=True, max_length=200)),
                ('actual_location', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('resolution_status', models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inventory.reconciliation')),
                ('tape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_results', to='inventory.tape')),
            ],
            options={
                'verbose_name': 'Reconciliation Result',
                'verbose_name_plural': 'Reconciliation Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
