# Generated by Django 6.0.6 on 2026-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_reconciliation_reconciliationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
