# Generated by Django 6.0.6 on 2026-06-23 07:19

import django.db.models.deletion
import django.utils.timezone
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_shipment_status_shipmentapprovalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('More Info Requested', 'More Info Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Dispatched', 'Dispatched'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Return Accepted', 'Return Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courier_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('employee_number', models.CharField(blank=True, max_length=50)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courier Profile',
                'verbose_name_plural': 'Courier Profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(default=inventory.models.generate_delivery_id, max_length=50, unique=True)),
                ('destination_location', models.CharField(max_length=200)),
                ('receiving_custodian', models.CharField(max_length=150)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Delayed', 'Delayed')], default='Delivered', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('manifest_matched', models.BooleanField(default=False)),
                ('all_tapes_delivered', models.BooleanField(default=False)),
                ('discrepancies_resolved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.courierprofile')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.shipment')),
            ],
            options={
                'verbose_name': 'Delivery Confirmation',
                'verbose_name_plural': 'Delivery Confirmations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_id', models.CharField(default=inventory.models.generate_exception_id, max_length=50, unique=True)),
                ('exception_type', models.CharField(choices=[('Missing Tape', 'Missing Tape'), ('Damaged Tape', 'Damaged Tape'), ('Incorrect Manifest', 'Incorrect Manifest'), ('Delivery Delay', 'Delivery Delay'), ('Custody Dispute', 'Custody Dispute'), ('Unexpected Tape', 'Unexpected Tape')], max_length=50)),
                ('description', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='inventory.shipment')),
                ('tape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='inventory.tape')),
            ],
            options={
                'verbose_name': 'Shipment Exception',
                'verbose_name_plural': 'Shipment Exceptions',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_id', models.CharField(default=inventory.models.generate_receipt_id, max_length=50, unique=True)),
                ('manifest_reference', models.CharField(blank=True, max_length=150)),
                ('pickup_date', models.DateField(default=django.utils.timezone.localdate)),
                ('pickup_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('pickup_location', models.CharField(max_length=200)),
                ('custody_confirmed', models.BooleanField(default=False)),
                ('confirmation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('all_tapes_scanned', models.BooleanField(default=False)),
                ('manifest_verified', models.BooleanField(default=False)),
                ('tape_count_matched', models.BooleanField(default=False)),
                ('no_damaged_tapes', models.BooleanField(default=True)),
                ('custody_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory.courierprofile')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Receipt',
                'verbose_name_plural': 'Shipment Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTransportEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Delayed', 'Delayed'), ('Delivered', 'Delivered'), ('Return Accepted', 'Return Accepted'), ('Return Delivered', 'Return Delivered')], max_length=50)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('event_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_events', to='inventory.courierprofile')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_events', to='inventory.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Transport Event',
                'verbose_name_plural': 'Shipment Transport Events',
                'ordering': ['-event_date', '-event_time', '-created_at'],
            },
        ),
    ]
