# Generated by Django 6.0.6 on 2026-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_customuser_role_reportlog_taperequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('More Info Requested', 'More Info Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Dispatched', 'Dispatched'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Return Accepted', 'Return Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
