# Generated by Django 6.0.6 on 2026-06-30 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0016_alter_shipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi bi-grid', max_length=100)),
                ('url_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi bi-circle', max_length=100)),
                ('url_name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.dashboardfeature')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='inventory.dashboardfeature')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_feature_permissions', to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Dashboard Feature Permission',
                'verbose_name_plural': 'Dashboard Feature Permissions',
                'ordering': ['role__name', 'feature__name'],
            },
        ),
    ]
