# Generated by Django 6.0.6 on 2026-06-30 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_dashboardfeature_dashboardfeatureitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardfeaturepermission',
            name='feature',
        ),
        migrations.AlterModelOptions(
            name='dashboardfeaturepermission',
            options={'ordering': ['role__name', 'feature_key'], 'verbose_name': 'Dashboard Feature Permission', 'verbose_name_plural': 'Dashboard Feature Permissions'},
        ),
        migrations.AddField(
            model_name='dashboardfeaturepermission',
            name='feature_key',
            field=models.CharField(choices=[('backup_dashboard', 'Dashboard'), ('add_tape', 'Add Tape'), ('tape_inventory', 'Tape Inventory'), ('shipments', 'Shipments'), ('reconciliation', 'Reconciliation'), ('reports', 'Reports'), ('audit_logs', 'Audit Logs'), ('operations_dashboard', 'Operations Dashboard'), ('shipment_approvals', 'Shipment Approvals'), ('exception_management', 'Exception Management')], default='', max_length=100, verbose_name='Feature'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DashboardFeatureExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('backup_dashboard', 'Dashboard'), ('add_tape', 'Add Tape'), ('tape_inventory', 'Tape Inventory'), ('shipments', 'Shipments'), ('reconciliation', 'Reconciliation'), ('reports', 'Reports'), ('audit_logs', 'Audit Logs'), ('operations_dashboard', 'Operations Dashboard'), ('shipment_approvals', 'Shipment Approvals'), ('exception_management', 'Exception Management')], max_length=100, verbose_name='Feature')),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_feature_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Dashboard Feature Exemption',
                'verbose_name_plural': 'Dashboard Feature Exemptions',
                'ordering': ['user__username', 'feature_key'],
            },
        ),
        migrations.DeleteModel(
            name='DashboardFeatureItem',
        ),
        migrations.DeleteModel(
            name='DashboardFeature',
        ),
    ]
