# Generated by Django 6.0.6 on 2026-07-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_dashboardfeaturepermission_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsetting',
            name='next_reconciliation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsetting',
            name='reconciliation_alert_duration_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='applicationsetting',
            name='reconciliation_alert_start_days_before',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
