# Generated by Django 6.0.6 on 2026-07-01 10:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_applicationsetting_next_reconciliation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SchemaChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=255)),
                ('detected_data_type', models.CharField(max_length=50)),
                ('target_table', models.CharField(max_length=255)),
                ('source_excel_filename', models.CharField(max_length=255)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sql_executed', models.TextField(blank=True)),
                ('synchronization_status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schema_changes', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_date', '-created_at'],
            },
        ),
    ]
