# Generated by Django 6.0.6 on 2026-07-01 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_auditlog_action_alter_auditlog_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Branch',
                'verbose_name_plural': 'Bank Branches',
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='BranchImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_records', models.PositiveIntegerField(default=0)),
                ('updated_records', models.PositiveIntegerField(default=0)),
                ('skipped_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('import_status', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('failed', 'Failed')], default='success', max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Import Log',
                'verbose_name_plural': 'Branch Import Logs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
