# Generated by Django 6.0.6 on 2026-07-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_auditlog_action_alter_auditlog_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='inventory.bankbranch'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='requesting_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='inventory.bankbranch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('auditor', 'IT Compliance Auditor'), ('user', 'User'), ('operations_manager', 'Operations Manager')], default='user', max_length=50),
        ),
    ]
