# Generated by Django 6.0.6 on 2026-07-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_courierprofile_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierprofile',
            name='vehicle_number',
            field=models.CharField(max_length=50),
        ),
    ]
