# Generated by Django 6.0.6 on 2026-07-03 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_courierprofile_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionCloseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_results', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approval_comment', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_close_requests', to=settings.AUTH_USER_MODEL)),
                ('exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_requests', to='inventory.shipmentexception')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exception Close Request',
                'verbose_name_plural': 'Exception Close Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
