# Generated by Django 6.0.6 on 2026-07-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_exceptioncloserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='scan_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='scan_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='total_tapes_expected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='total_tapes_scanned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tape',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tape',
            name='last_scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tapes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tape',
            name='scan_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tape',
            name='scan_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Scanning', 'Scanning'), ('Scanned', 'Scanned'), ('Verified', 'Verified'), ('Exception', 'Exception')], db_index=True, default='Pending', max_length=20),
        ),
    ]
