# Generated by Django 6.0.6 on 2026-07-06 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_reconciliation_assigned_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='return_assigned_courier_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_assignments', to='inventory.courierprofile'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='return_assigned_courier_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_return_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='return_courier_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='return_courier_response_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='return_request_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='return_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('More Info Requested', 'More Info Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Dispatched', 'Dispatched'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Return Requested', 'Return Requested'), ('Return Accepted', 'Return Accepted'), ('Return In Transit', 'Return In Transit'), ('Return Rejected', 'Return Rejected'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmenttransportevent',
            name='event_type',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Delayed', 'Delayed'), ('Delivered', 'Delivered'), ('Return Requested', 'Return Requested'), ('Return Accepted', 'Return Accepted'), ('Return Rejected', 'Return Rejected'), ('Return Delivered', 'Return Delivered')], max_length=50),
        ),
    ]
