# Generated by Django 6.0.6 on 2026-07-08 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_shipment_return_assigned_courier_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='approval_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_supreme', 'Awaiting Supreme Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='shipment',
            name='approved_by_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_approved_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='approved_by_supreme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supreme_approved_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
