# Generated by Django 6.0.6 on 2026-07-09 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_shipment_approval_stage_shipment_approved_by_backup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardfeatureexemption',
            name='feature_key',
            field=models.CharField(choices=[('backup_dashboard', 'Dashboard'), ('add_tape', 'Add Tape'), ('tape_inventory', 'Tape Inventory'), ('shipments', 'Shipments'), ('reconciliation', 'Reconciliation'), ('reports', 'Reports'), ('audit_logs', 'Audit Logs'), ('operations_dashboard', 'Operations Dashboard'), ('shipment_approvals', 'Shipment Approvals'), ('warehouse_operations_dashboard', 'Warehouse Operations Dashboard'), ('exception_management', 'Exception Management')], max_length=100, verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='dashboardfeaturepermission',
            name='feature_key',
            field=models.CharField(choices=[('backup_dashboard', 'Dashboard'), ('add_tape', 'Add Tape'), ('tape_inventory', 'Tape Inventory'), ('shipments', 'Shipments'), ('reconciliation', 'Reconciliation'), ('reports', 'Reports'), ('audit_logs', 'Audit Logs'), ('operations_dashboard', 'Operations Dashboard'), ('shipment_approvals', 'Shipment Approvals'), ('warehouse_operations_dashboard', 'Warehouse Operations Dashboard'), ('exception_management', 'Exception Management')], max_length=100, verbose_name='Feature'),
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=20)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Awaiting Supreme Approval', 'Awaiting Supreme Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Clarification Requested', 'Clarification Requested')], default='Pending', max_length=40)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_deadline', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('requested_changes', models.JSONField(blank=True, default=list)),
                ('related_object_id', models.CharField(blank=True, max_length=255)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('audit_history', models.JSONField(blank=True, default=list)),
                ('attachment_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pending_requests', to=settings.AUTH_USER_MODEL)),
                ('backup_administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendingapproval_backups', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendingapprovals', to='inventory.bankbranch')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendingapproval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pending_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
    ]
