# Generated by Django 6.0.6 on 2026-07-10 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_role_userroleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('system_administrator', 'System Administrator'), ('system administrator', 'System Administrator'), ('backup', 'Backup Administrator'), ('backup_administrator', 'Backup Administrator'), ('backup administrator', 'Backup Administrator'), ('operations', 'Operations Manager'), ('operations_manager', 'Operations Manager'), ('operations manager', 'Operations Manager'), ('warehouse', 'Warehouse Operations'), ('warehouse_operations', 'Warehouse Operations'), ('warehouse operations', 'Warehouse Operations'), ('warehouse ops', 'Warehouse Operations'), ('supreme', 'Supreme Approver'), ('supreme_approver', 'Supreme Approver'), ('supreme approver', 'Supreme Approver'), ('auditor', 'Compliance Auditor'), ('compliance_auditor', 'Compliance Auditor'), ('compliance auditor', 'Compliance Auditor'), ('information_security_officer', 'Information Security Officer'), ('information security officer', 'Information Security Officer'), ('security', 'Information Security Officer'), ('courier', 'Courier'), ('dr', 'DR Team'), ('dr_team', 'DR Team'), ('dr team', 'DR Team'), ('user', 'User')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='dashboard_key',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('system_administrator', 'System Administrator'), ('system administrator', 'System Administrator'), ('backup', 'Backup Administrator'), ('backup_administrator', 'Backup Administrator'), ('backup administrator', 'Backup Administrator'), ('operations', 'Operations Manager'), ('operations_manager', 'Operations Manager'), ('operations manager', 'Operations Manager'), ('warehouse', 'Warehouse Operations'), ('warehouse_operations', 'Warehouse Operations'), ('warehouse operations', 'Warehouse Operations'), ('warehouse ops', 'Warehouse Operations'), ('supreme', 'Supreme Approver'), ('supreme_approver', 'Supreme Approver'), ('supreme approver', 'Supreme Approver'), ('auditor', 'Compliance Auditor'), ('compliance_auditor', 'Compliance Auditor'), ('compliance auditor', 'Compliance Auditor'), ('information_security_officer', 'Information Security Officer'), ('information security officer', 'Information Security Officer'), ('security', 'Information Security Officer'), ('courier', 'Courier'), ('dr', 'DR Team'), ('dr_team', 'DR Team'), ('dr team', 'DR Team'), ('user', 'User')], max_length=50),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('menu_group', models.CharField(default='General', max_length=120)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('url_name', models.CharField(blank=True, max_length=120)),
                ('url_params', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('sidebar_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('requires_audit', models.BooleanField(default=False)),
                ('scope', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_features', to='inventory.feature')),
            ],
            options={
                'ordering': ['menu_group', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_feature_assignments', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_features', to='inventory.feature')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_features', to='inventory.role')),
            ],
            options={
                'ordering': ['role__name', 'feature__menu_group', 'feature__display_order'],
                'unique_together': {('role', 'feature')},
            },
        ),
        migrations.DeleteModel(
            name='UserRoleAssignment',
        ),
    ]
