# Generated by Django 6.0.6 on 2026-07-14 13:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_customuser_role_alter_role_dashboard_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='roles', through='inventory.RoleFeature', to='inventory.feature'),
        ),
        migrations.AddField(
            model_name='tape',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Backup Approved', 'Backup Approved'), ('Supreme Approved', 'Supreme Approved'), ('Active', 'Active'), ('Rejected', 'Rejected')], default='Pending', max_length=40)),
                ('is_primary_dashboard', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('backup_approved_at', models.DateTimeField(blank=True, null=True)),
                ('supreme_approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('audit_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('backup_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_backup_approved', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='inventory.role')),
                ('supreme_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_supreme_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
